# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'text recognising' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Extractor
#  pod 'Firebase/Core'
#  pod 'Firebase/MLVision'
#  pod 'Firebase/MLVisionTextModel'
	#устанавливай если используешь распознавание текста кроме как на англ языке
#	pod 'GoogleMLKit/TextRecognition'
	
end
